### ISSUE TITLE
OpenTTD on F-Droid

### ISSUE THREAD

**Issue by RiQuY** [pelya/openttd-android#1]
I tried searching OpenTTD on F-Droid and I discovered that the app were available there in the past but now it doesn't exist on F-Droid.
How did this happened?
Can you please upload the app to F-Droid? It is a privacy-friendly app store and the apps in there don't require Google Play Services.
Thank you.

**Comment by pelya** [comment]
I've submitted OpenTTD build script to F-Droid a while ago, but it failed
to download some external dependencies, build failed, and I did not try
again.
https://gitlab.com/fdroid/fdroiddata/merge_requests/963

**Comment by RiQuY** [comment]
OpenTTD is present on F-Droid now. https://f-droid.org/es/packages/org.openttd.fdroid/ 
I close this issue.
