### ISSUE TITLE
Latest Update

### ISSUE THREAD

**Issue by TransportTyphoon** [pelya/openttd-android#10]
1.11.0 update for Android

Prior to update everything worked perfectly

Now unable to fast forward. Icon remains active but gameplay speed remains normal. Fast forward results in increased speed for 3 seconds before reverting to normal tempo.

Also unable to save since update.

**Comment by pelya** [comment]
I've reproduced the problem with fast forward.

Saving works okay for me. Are you using network save? Could you start a new
game and try to save?

**Comment by pelya** [comment]
Please do a screenshot of the missing Save button (hold Volume Down + Power)

**Comment by TransportTyphoon** [comment]
Having started new game, the save fuction was there. Interestingly, when returning to my original game the save fuctionality had returned. 
However, fast forward is still not working correctly. The new game experienced similar but not as severe issues regarding fast forward function. With new load, instead of working for 3 seconds before returning to normal speed like in my original game, this new load jerks. Fast for a few seconds, then slow, then fast.

**Comment by pelya** [comment]
Fast forward should be fixed in 1.11.2 update.
