### ISSUE TITLE
Game crash upon save

### ISSUE THREAD

**Issue by Arcen3** [pelya/openttd-android#11]
## Version of OpenTTD
1.11.2

## Expected result
Expected saving of game

## Actual result
Game directly closes without any error messages

## Steps to reproduce
Unknown cause, however earlier in game cheats was used to bring time to 1990, and yapf.rail_firstred_twoway_eol was set to on.

Android version 11
Phone: Samsung Galaxy Note 20 Ultra
![Screenshot_20210514-215507_OpenTTD](https://user-images.githubusercontent.com/60306919/118280979-4dcef100-b4ff-11eb-9746-633e7931347e.jpg)
![Screenshot_20210514-215501_OpenTTD](https://user-images.githubusercontent.com/60306919/118280988-50314b00-b4ff-11eb-81dc-140bc01eae60.jpg)

[save.zip](https://github.com/pelya/openttd-android/files/6479240/save.zip)

This zip file should contain the 3 save files. Prior to this the game was never loaded from network and it was after the crash did I have to load from network.

**Comment by Arcen3** [comment]
I am trying to attach the save files,
 error message on the files just says "file not readable"

**Comment by pelya** [comment]
The crash should be fixed in version 1.11.2.rev107, you should get the
update tomorrow.
