### ISSUE TITLE
Scrolling the world map

### ISSUE THREAD

**Issue by andraaspar** [pelya/openttd-android#2]
First of all, a big thank you for porting this to Android, it's lots of fun and I really appreciate your work.

It seems like the world map is really difficult to scroll now. I tried various settings and just can't get it right. It seems like I need to press the centering button to move it at all. Any chance for dragging it either by one or by two fingers? I think one finger drag was the standard until now. I'm on Android 9 if that helps. Thank you!

**Comment by pelya** [comment]
Yes, it's broken. Thanks for bugreport, I'll fix it in the next release.

**Comment by pelya** [comment]
Fixed in 1.10.3
