### ISSUE TITLE
Tram type menu missing

### ISSUE THREAD

**Issue by isaacrdc** [pelya/openttd-android#7]
## Version of OpenTTD
1.10.90
## Expected result
Tramtype menu will show up, when there is a grf loaded.

## Actual result
It doesn't show up in actual game even I have the requirements eg. Tramtype grf, trams grf. I think this is similar to issue #6, there is no problem in Scenario editor (see the first pic)
![Screenshot_20201109-180954_OpenTTD](https://user-images.githubusercontent.com/63526673/98529113-385edd00-22b8-11eb-85b1-7abf99562689.jpg)
But here it doesn't show up (actual game), even I press the "Streetcar construction" button.
![Screenshot_20201109-181049_OpenTTD](https://user-images.githubusercontent.com/63526673/98529309-6ba16c00-22b8-11eb-9b08-b66ed626ea64.jpg)

## Steps to reproduce
Just like normal steps when loading grf and playing the game.
2cc trams grf
U&raTT grf

**Comment by pelya** [comment]
Should be fixed in 1.11.0-RC1.rev99
